#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso interface_SNOWPACK
wclean libso topBoundaryLayerAdditionRemovalTopoFvMesh1
wclean
#------------------------------------------------------------------------------
