#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r log.*

# Get application directory
application=`getApplication`

echo $application

runApplication blockMesh

runApplication $application
